version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB_NAME}
    ports:
      - '${PSQL_PORT}:${PSQL_PORT}'
    volumes:
      - database-volume:/var/lib/postgresql/data
volumes:
  database-volume: