version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB_NAME}
    ports:
      - '${PSQL_PORT}:${PSQL_PORT}'
    volumes:
      - database-volume:/var/lib/postgresql/data
  node:
    build: ./
    stop_signal: SIGINT
    depends_on:
      - postgres
    ports:
      - '80:80'
      - '443:443'
    environment:
      NODE_ENV: production
      PSQL_HOST: postgres
      PSQL_PORT: ${PSQL_PORT}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASS: ${PSQL_PASS}
      PSQL_DB_NAME: ${PSQL_DB_NAME}
volumes:
  database-volume: