services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database-volume:/var/lib/postgresql/data
  node:
    build: ./
    stop_signal: SIGINT
    depends_on:
      - postgres
    ports:
      - '80:80'
    environment:
      IS_PROD: 1
      PSQL_HOST: postgres
      DOCKER_PSQL_EXTERNAL_PORT: ${DOCKER_PSQL_EXTERNAL_PORT}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASS: ${PSQL_PASS}
      PSQL_DB_NAME: ${PSQL_DB_NAME}
volumes:
  database-volume: